### ISSUE TITLE
Collect all vendor packages in one repository

### ISSUE THREAD

**Issue by oysstu** [gazebo-release/gz_sim_vendor#3]
Would it make sense to collect all vendor packages in a repository? I'm sure there's some reason (e.g., CI) to have them as individual repositories. Would it be possible to have either
- A repository with a gz-vendor.repos file (similar to https://github.com/ros2/ros2)
- A repository with git submodules to all vendor packages

This would make it a bit more convenient to use non-ubuntu / source gazebo packages.

**Comment by azeey** [comment]
> Would it make sense to collect all vendor packages in a repository?

This might be possible, but at the time of development, we needed to move faster on some of the packages since they were part of ROS core (eg. gz-math) and some weren't. Making the change to a single repository would be nice since it would allow us to make releases with a single bloom call. However, it won't be trivial so probably not going to be a priority right now.

It should be possible to add a `gz-vendor.repos` file in https://github.com/gazebo-tooling/gz_vendor (PRs welcome). In the meantime, there's one linked in https://gazebosim.org/docs/latest/ros2_gz_vendor_pkgs/#gazebo-library-development-with-vendor-packages

**Comment by oysstu** [comment]
> It should be possible to add a `gz-vendor.repos` file in https://github.com/gazebo-tooling/gz_vendor (PRs welcome). 

Should the gz_vendor repo then have 'rolling' and 'jazzy' branches instead of a single main branch? The .repos file can then target the respective branches in the vendor repos

> In the meantime, there's one linked in https://gazebosim.org/docs/latest/ros2_gz_vendor_pkgs/#gazebo-library-development-with-vendor-packages

Great, didn't see that one already existed. Would be good to have it a repository instead of a gist though

**Comment by azeey** [comment]
@oysstu https://github.com/gazebo-tooling/gz_vendor/pull/5
